### ISSUE TITLE
Sharing a helpful resource for improving the prayer-times website

### ISSUE THREAD

**Issue by massoudsalem** [AmrSaber/prayer-times#1]
Hi there! I came across your prayer-times website and I must say, it looks good. I just wanted to share something interesting with you. Recently, I forked the repository to make some tweaks, but then I stumbled upon an impressive open-source extension called PrayTimes that suits my needs better, so I gave up tweaking yours. Upon revisiting it at [praytimes.org](http://praytimes.org/code/), I think it could be a great addition to your project. Although I know your code is meant to be simple, I believe this extension could inspire you. Alternatively, you could consider making it a browser extension for better accessibility or even publishing it to browsers' stores as a way to seek reward from Allah Almighty.

Have a nice day!

**Comment by AmrSaber** [comment]
Hello @massoudsalem,

First of all, sorry for responding so late. Second, thanks for your suggestions, but I have some comments.

Regarding integrating praytimes.org: I don't want to integrate with some calculation app (I know several others who do this, or I could do the calculations on my own), bit the goal of this project is to just follow a near by mosque instead of going through all the different configurations and hope that the end result matches that of the mosque you pray at (I went through this already with several mobile apps).

Regarding the part for the extension: I think this will indeed be helpful, I think it's a good idea in general, and I might work on it when I have some time. But it will need the application to be generalised a bit to include different countries and cities, and that's something I am not if it has an audience or not really.

Lastly, I am closing this issue, but feel free to respond if you wish.
